#Makefile to run the programm
run: 
	cd /home/guignet/Documents/code/AoC/AdventOfCode/day09 ; /usr/bin/env /usr/lib/jvm/java-11-openjdk-amd64/bin/java -agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:34947 -cp /home/guignet/Documents/code/AoC/AdventOfCode/day09/demo/target/classes com.day09.App